version: '3.8'

services:
  mysql-db:
   image: mysql:8
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: mydb
    MYSQL_USER: myuser
    MYSQL_PASSWORD: myuserpass
   ports:
    - "3306:3306"
   volumes:
    - mysql_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
    depends_on:
      - mysql-db

  backend:
    build: ./backend
    deploy:
      replicas: 3
    depends_on:
      - mysql-db

  frontend:
    build: ./frontend
    deploy:
      replicas: 3
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
